# CẤU HÌNH SERVER
server.port=8080

# KẾT NỐI DATABASE MYSQL
# Đã sửa tên DB thành bluemoon_db và thêm ép kiểu Tiếng Việt UTF-8
spring.datasource.url=jdbc:mysql://localhost:3306/bluemoon_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CẤU HÌNH HIBERNATE / JPA
# Tự động cập nhật bảng (không xóa dữ liệu cũ)
spring.jpa.hibernate.ddl-auto=update
# Hiển thị câu lệnh SQL ra console để dễ debug
spring.jpa.show-sql=true
# Định dạng câu lệnh SQL cho dễ nhìn (Nên thêm dòng này)
spring.jpa.properties.hibernate.format_sql=true
